Standardize qudt:symbol for a few units
qudt/qudt-public-repo pull request #797
Opened 2023-10-27 13:04 UTC by mgberg

Just standardizes a few unit symbols to match the rest of the symbols.

Note that I used `TOR` for Ton of Refrigeration because it seems to be commonly used but doesn't conflict with the symbol for Register Ton.

2023-10-27 15:24 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
> +  qudt:symbol "kft³" ;
What would be the symbol for (1000 feet)**3, as compared with this unit, which is 1000 (cubic feet)?

2023-10-31 13:56 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
> +  qudt:symbol "kft³" ;
Either variant of the symbol still leaves me with the question of how to interpret it unambiguously. It seems to me that the only recourse is the use of parentheses, if we are to include a symbol at all. What about k(ft³)?

2023-10-31 14:30 UTC, steveraysteveray requested changes
Something strange happened, and the previous xsd:double versions of conversionMultiplier for some units (e.g. PlanckPressure and other Planck units) have reappeared. Everything else seems fine. Could you fix?

2023-10-31 14:50 UTC, mgberg commented
> Something strange happened, and the previous xsd:double versions of conversionMultiplier for some units (e.g. PlanckPressure and other Planck units) have reappeared. Everything else seems fine. Could you fix?

@steveraysteveray That's strange! When I open the file in Composer, it converts from the scientific notation to the long format. Is there a setting in Composer I'm missing to prevent that from happening? If not, that'll make it challenging to use Composer going forward to edit units.

2023-10-31 15:08 UTC, steveraysteveray approved these changes

2023-10-31 15:08 UTC, merged

2023-10-31 15:09 UTC, steveraysteveray commented
@mgberg, I could not recreate your problem, but I see you fixed it. What was the issue?