Added units
qudt/qudt-public-repo pull request #893
Opened 2024-04-09 13:40 UTC by gezever

Added units to publish the flow of pollution caused by factories on a yearly base, as required by EU-laws.

2024-04-09 13:49 UTC, steveraysteveray requested changes

2024-04-09 13:49 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
> +unit:HR-PER-YR
To be even more sophisticated, consider adding a numerator and denominator dimension vector (each with dimension of time) as described [here](https://github.com/qudt/qudt-public-repo/wiki/User-Guide-for-QUDT#6-using-quantity-kinds-with-dimensionless-quantities).

2024-04-09 13:49 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
> +    qudt:conversionMultiplier 3.168808781e-8 ;
Should be 
qudt:conversionMultiplier 0.00000003168808781 ;
qudt:conversionMultiplierSN 3.168808781E-8 ;

2024-04-09 14:35 UTC, gezever commented
@steveraysteveray 
I committed the suggested corrections.

2024-04-09 14:54 UTC, steveraysteveray approved these changes

2024-04-09 14:54 UTC, merged

2024-04-09 14:57 UTC, gezever commented
@steveraysteveray 
Thank You

2024-04-09 16:44 UTC, steveraysteveray commented
@fkleedorfer, you are correct that two of the three units use "year" rather than "yr", which should be corrected, although we do not have a validation rule or algorithm to ensure consistency.

More broadly though, the multiple symbols raise some options worth discussing:

Should we:
1. Disallow multiple symbols
2. Allow multiple symbols, each with a different language tag (like we do with rdfs:label)
3. Allow multiple symbols, possibly with the same language tag

These three new units are the only ones with more than one symbol at present. However, it's possible there there exist some units with alternate symbols, yes?
Currently we do not validate against any of the three options above. Should we?

We do want symbols to be represented using Unicode.

2024-04-09 17:03 UTC, fkleedorfer commented
I'm on team 1. we thus avoid the problem of having to choose one, and we have a clear path toward automatic symbol generation/verification

2024-04-10 11:27 UTC, fkleedorfer commented
I think there is a lot more to say about this topic, so I started a [discussion about it](https://github.com/qudt/qudt-public-repo/discussions/895)