New unit: Swiss Francs per kilogram
qudt/qudt-public-repo pull request #945
Opened 2024-07-08 08:30 UTC by tpluscode

I would like to propose a new unit which will be used at [Lindas Linked Data Services](https://lindas.admin.ch/) to publish Swiss open data

2024-07-16 14:33 UTC, steveraysteveray requested changes
One item that is still missing is the quantity kind CostPerMass that your unit can then point to.

2024-07-16 14:33 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
>    qudt:conversionMultiplierSN 1.0E-3 ;
Since the kilogram is the base SI unit, the conversion multipliers should be 1.0

2024-07-16 15:33 UTC, tpluscode commented
> One item that is still missing is the quantity kind CostPerMass that your unit can then point to.

Shall I add it in the PR?

2024-07-16 17:19 UTC, steveraysteveray requested changes
The quantity kind and unit need triples for qudt:hasDimensionVector
Namely:
  qudt:hasDimensionVector qkdv:A0E0L0I0M-1H0T0D0 ;

Also, a brief triple for qudt:plainTextDescription.

See https://github.com/qudt/qudt-public-repo/wiki/QuantityKind-Vocabulary-Submission-Guidelines

2024-07-16 17:19 UTC, steveraysteveray commented on vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
>    qudt:conversionMultiplier 0.001 ;
This one needs to be 1.0
The SN one needs to be 1.0E0

2024-07-17 15:33 UTC, tpluscode commented
Thank you for your pointers @steveraysteveray

2024-07-17 16:01 UTC, steveraysteveray approved these changes

2024-07-17 16:01 UTC, merged